import Head from 'next/head'
import Link from 'next/link'
import Heading from '../components/Heading'
import getAllPost from '../utils/getAllPost'

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>All Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-10">
        <Heading str="Blog" />
        <section className="grid mt-6 grids-cols-1 md:grid-cols-2 gap-6">
          {posts.map((post) => (
            <Link href={`/post/${post.slug}`} key={post.slug}>
              <article className="border border-black/10 hover:border-black/20 p-4 rounded-md cursor-pointer hover:shadow-md transition-all duration-300">
                <h2 className="text-xl text-pink-400 font-semibold">
                  {post.data.title}
                </h2>
                <time className="text-xs mt-2 inline-block text-gray-500">
                  {post.data.date}
                </time>
              </article>
            </Link>
          ))}
        </section>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const posts = await getAllPost()

  return {
    props: {
      posts,
    },
  }
}
