import Head from 'next/head'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Link from 'next/link'

export default function Home({ posts }) {
  console.log(posts)
  return (
    <>
      <Head>
        <title>All Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="mt-10 flex flex-col gap-8">
        {posts.map((post) => (
          <Link href={`/post/${post.slug}`} key={post.title}>
            <article className="cursor-pointer">
              <h2 className="text-xl text-pink-500 font-semibold">
                {post.frontMatter.title}
              </h2>
              <div className="mt-1">
                <p className="text-sm">{post.frontMatter.date}</p>
                <p>{post.frontMatter.desc}</p>
              </div>
            </article>
          </Link>
        ))}
      </section>
    </>
  )
}

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'))
  const posts = files.map((filename) => {
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const { data: frontMatter } = matter(markdownWithMeta)
    return {
      frontMatter,
      slug: filename.split('.')[0],
    }
  })
  return {
    props: {
      posts,
    },
  }
}
